export const FETCH_MEMBERS = "FETCH_MEMBERS";
export const CREATE_MEMBER = "CREATE_MEMBER";
export const CREATE_MEMBER_ERROR = "CREATE_MEMBER_ERROR";
export const CLEAR_CREATE_MEMBER_ERROR = "CLEAR_CREATE_MEMBER_ERROR";
